# Generated by Django 5.2.3 on 2025-07-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_registration', models.CharField(help_text='GST/VAT', max_length=100)),
                ('primary_contact_full_name', models.CharField(max_length=255)),
                ('primary_contact_title', models.CharField(max_length=100)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('primary_contact_phone', models.CharField(max_length=20)),
                ('billing_address', models.TextField()),
                ('billing_contact_name', models.CharField(max_length=255)),
                ('payment_details', models.CharField(help_text='Do not store raw card details in production.', max_length=255)),
            ],
        ),
    ]
