# Generated by Django 5.2.3 on 2025-07-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='billing_contact_name',
        ),
    ]
