# Generated by Django 5.2.3 on 2025-07-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_client_billing_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='primary_contact_email',
        ),
    ]
