# Generated by Django 5.2.3 on 2025-07-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_client_primary_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
