version: '3.9'

services:
  frontend:
    build: ./frontend
    # NO ports exposed - internal only
    environment:
      - VITE_API_URL=/api/
    volumes:
      - emesa_frontend_dist:/app/dist
    depends_on:
      - backend
    networks:
      - emesa_net

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - emesa_net
    # No ports exposed; only accessible via nginx

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: emesa_db
      MYSQL_USER: emesa_user
      MYSQL_PASSWORD: 'Emesa@123'
      MYSQL_ROOT_PASSWORD: '#Mysql@123'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro  # Auto-run init script
    networks:
      - emesa_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "emesa_user", "-pEmesa@123"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/media:/app/media
      - emesa_frontend_dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - emesa_net

networks:
  emesa_net:
    driver: bridge

volumes:
  db_data:
  emesa_frontend_dist: 