# Generated by Django 5.2.4 on 2025-07-11 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField()),
                ('step_file', models.FileField(upload_to='step_files/')),
                ('quantity', models.PositiveIntegerField()),
                ('material_thickness', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=100)),
                ('material_grade', models.CharField(max_length=100)),
                ('surface_treatment', models.CharField(max_length=100)),
                ('packing_standard', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('accepted', 'Accepted'), ('in_production', 'In Production'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='under_review', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='orders.supplier'),
        ),
    ]
