# Generated by Django 5.2.4 on 2025-07-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_machine_capabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
