# Generated by Django 5.2.4 on 2025-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('counter_offer', 'Counter Offer'), ('system', 'System')], default='message', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('negotiation', 'Negotiation'), ('awaiting_payment', 'Awaiting Payment'), ('accepted', 'Accepted'), ('in_production', 'In Production'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
