# Generated by Django 5.2.4 on 2025-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_agreed_price_order_payment_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='d2_draft_design',
            field=models.FileField(default='NULL', upload_to='draft_designs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='part_id',
            field=models.CharField(default='NULL', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='step_file',
            field=models.FileField(blank=True, null=True, upload_to='step_files/'),
        ),
    ]
