# Generated by Django 5.2.3 on 2025-07-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_d2_draft_design_order_part_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='max_capacity',
            new_name='bed_length',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='is_available',
        ),
        migrations.AddField(
            model_name='machine',
            name='bed_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='make',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='tonnage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('laser', 'Laser'), ('bending', 'Bending'), ('punch', 'Punch')], default='laser', max_length=100),
        ),
    ]
