# Generated by Django 5.2.3 on 2025-07-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_max_capacity_machine_bed_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='machine_photos/'),
        ),
    ]
