# Generated by Django 5.2.3 on 2025-07-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_machine_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='photo',
        ),
    ]
