# Generated by Django 5.2.3 on 2025-07-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_machine_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='machine_photos/'),
        ),
    ]
